### ISSUE TITLE
Find a grocery API instead of Walmart API

### ISSUE THREAD

**Issue by LuzanneB** [LuzanneB/Project1#9]

**Comment by LuzanneB** [comment]
if we can't find shopping API will need to shift our plan

**Comment by Nova-Xue** [comment]
we are going to use usda instead and create http url for shopping part

**Comment by Nova-Xue** [comment]
Or wiki

**Comment by Nova-Xue** [comment]
MediaWiki will be our second api
https://www.mediawiki.org/wiki/MediaWiki
